In [1]:
import pandas as pd

**CLEANING DATAFRAME**

In [2]:
df = pd.read_csv("scraped_results.csv")

In [3]:
df.head()

,brand,id,metadata.creationDate,metadata.updateDate,sections.location.address.city,sections.location.address.zipCode,sections.location.address.country,sections.location.geometry.type,sections.location.geometry.coordinates,sections.description.description,sections.description.headline,sections.hardFacts.title,sections.hardFacts.keyfacts,sections.hardFacts.price.value,numberOfRooms,livingSpace,numberOfFloors,numberOfBedrooms,availability,plotSpace
0,seloger,25EC9GDFBT55,2025-11-20T08:56:00Z,2025-11-23T01:16:54.498Z,Paris 6ème,75006,FRA,Point,"[2.3387919, 48.8536809]",## Space\r\n\r\nThis accommodation is availabl...,Appartement de 34m2,Appartement à louer,"['1 pièce', '34 m²', '1er étage']",2 800 €,1 pièce,34 m²,1er étage,NaN,NaN,NaN
1,seloger,2524YZ9M2KYE,2025-11-06T14:14:00Z,2025-11-19T17:36:08.608Z,Lyon 5ème,69005,FRA,Point,"[4.794783, 45.758385]","26 B, rue des Aqueducs 69005 Lyon, au cœur du ...","Location F4 - 26 B, rue des Aqueducs 69005 Lyon",Appartement à louer,"['4 pièces', '3 chambres', '91,7 m²', 'Étage 7...",1 666 €,4 pièces,"91,7 m²",Étage 7/7,3 chambres,NaN,NaN
2,seloger,24KPL52W4HXP,2024-03-05T14:14:00Z,2025-10-30T01:20:07.218Z,Lyon 6ème,69006,FRA,Point,"[4.844802, 45.768051]",Au coeur du quartier FOCH - au 17 rue de Sèze ...,Appartement 3 pièces,Appartement à louer,"['3 pièces', '2 chambres', '63,5 m²', '4ème ét...",1 440 €,3 pièces,"63,5 m²",4ème étage,2 chambres,NaN,NaN
3,seloger,25IIW65P1F9X,2025-10-29T16:55:44.0438727Z,2025-10-29T16:55:44.0438708Z,Lyon,69005,FR,Point,"[4.827683999999999, 45.76254799999993]",Particulier loue F3 bis de 85 m² rue St Jean d...,ST JEAN 85m² grand T3 bis bcp cachet sans vis ...,Appartement à louer,"['3 pièces', '2 chambres', '85 m²', 'Étage 1/4']",1 280 €,3 pièces,85 m²,Étage 1/4,2 chambres,NaN,NaN
4,seloger,25U9XDRKUJ3L,2025-07-04T09:35:00Z,2025-08-09T16:36:10.882Z,Lyon 1er,69001,FRA,MultiPolygon,"[[[[4.8269, 45.77195], [4.828, 45.77154], [4.8...",LYON 4E ARRONDISSEMENT- A LOUER Studio de 20m²...,Appartement - Studio - LYON 4E ARRONDISSEMENT ...,Appartement à louer,"['1 pièce', '20 m²']",560 €,1 pièce,20 m²,NaN,NaN,NaN,NaN

In [18]:
df.describe()

,brand,id,metadata.creationDate,metadata.updateDate,sections.location.address.city,sections.location.address.zipCode,sections.location.address.country,sections.location.geometry.type,sections.location.geometry.coordinates,sections.description.description,sections.description.headline,sections.hardFacts.title,sections.hardFacts.keyfacts,sections.hardFacts.price.value,numberOfRooms,livingSpace,numberOfFloors,numberOfBedrooms,availability,plotSpace
count,2937,2937,2937,2937,2935,2937,2937,2937,2937,2937,2937,2937,2937,2937,2933,2928,2691,2234,356,7
unique,1,2937,2260,2935,33,34,2,2,2276,2902,1910,11,2496,1158,11,649,133,9,72,7
top,seloger,25EC9GDFBT55,2025-10-08T15:11:00Z,2025-11-23T01:17:05.734Z,Lyon 3ème,69003,FRA,Point,"[[[[4.89486, 45.74378], [4.89188, 45.7391], [4...",## Space\r\n\r\n Nichée au 3 € étage d'un gran...,Appartement,Appartement à louer,"['1 pièce', '15 m²', '1er étage']",1 800 €,2 pièces,15 m²,1er étage,1 chambre,dès le 01/12/2025,300 m² de terrain
freq,2937,1,39,2,239,250,2833,1875,17,4,112,2617,9,37,937,58,343,1077,33,1

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2937 entries, 0 to 2936
Data columns (total 20 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   brand                                   2937 non-null   object
 1   id                                      2937 non-null   object
 2   metadata.creationDate                   2937 non-null   object
 3   metadata.updateDate                     2937 non-null   object
 4   sections.location.address.city          2935 non-null   object
 5   sections.location.address.zipCode       2937 non-null   object
 6   sections.location.address.country       2937 non-null   object
 7   sections.location.geometry.type         2937 non-null   object
 8   sections.location.geometry.coordinates  2937 non-null   object
 9   sections.description.description        2937 non-null   object
 10  sections.description.headline           2937 non-null   object
 11  sections.hardFacts.title                2937 non-null   object
 12  sections.hardFacts.keyfacts             2937 non-null   object
 13  sections.hardFacts.price.value          2937 non-null   object
 14  numberOfRooms                           2933 non-null   object
 15  livingSpace                             2928 non-null   object
 16  numberOfFloors                          2691 non-null   object
 17  numberOfBedrooms                        2234 non-null   object
 18  availability                            356 non-null    object
 19  plotSpace                               7 non-null      object
dtypes: object(20)
memory usage: 459.0+ KB

In [20]:
df.drop(["availability" , "plotSpace"],axis=1,inplace=True)

In [21]:
df

,brand,id,metadata.creationDate,metadata.updateDate,sections.location.address.city,sections.location.address.zipCode,sections.location.address.country,sections.location.geometry.type,sections.location.geometry.coordinates,sections.description.description,sections.description.headline,sections.hardFacts.title,sections.hardFacts.keyfacts,sections.hardFacts.price.value,numberOfRooms,livingSpace,numberOfFloors,numberOfBedrooms
0,seloger,25EC9GDFBT55,2025-11-20T08:56:00Z,2025-11-23T01:16:54.498Z,Paris 6ème,75006,FRA,Point,"[2.3387919, 48.8536809]",## Space\r\n\r\nThis accommodation is availabl...,Appartement de 34m2,Appartement à louer,"['1 pièce', '34 m²', '1er étage']",2 800 €,1 pièce,34 m²,1er étage,NaN
1,seloger,2524YZ9M2KYE,2025-11-06T14:14:00Z,2025-11-19T17:36:08.608Z,Lyon 5ème,69005,FRA,Point,"[4.794783, 45.758385]","26 B, rue des Aqueducs 69005 Lyon, au cœur du ...","Location F4 - 26 B, rue des Aqueducs 69005 Lyon",Appartement à louer,"['4 pièces', '3 chambres', '91,7 m²', 'Étage 7...",1 666 €,4 pièces,"91,7 m²",Étage 7/7,3 chambres
2,seloger,24KPL52W4HXP,2024-03-05T14:14:00Z,2025-10-30T01:20:07.218Z,Lyon 6ème,69006,FRA,Point,"[4.844802, 45.768051]",Au coeur du quartier FOCH - au 17 rue de Sèze ...,Appartement 3 pièces,Appartement à louer,"['3 pièces', '2 chambres', '63,5 m²', '4ème ét...",1 440 €,3 pièces,"63,5 m²",4ème étage,2 chambres
3,seloger,25IIW65P1F9X,2025-10-29T16:55:44.0438727Z,2025-10-29T16:55:44.0438708Z,Lyon,69005,FR,Point,"[4.827683999999999, 45.76254799999993]",Particulier loue F3 bis de 85 m² rue St Jean d...,ST JEAN 85m² grand T3 bis bcp cachet sans vis ...,Appartement à louer,"['3 pièces', '2 chambres', '85 m²', 'Étage 1/4']",1 280 €,3 pièces,85 m²,Étage 1/4,2 chambres
4,seloger,255ZQMFK4DAT,2025-11-03T10:08:08.2828323Z,2025-11-03T10:39:14.8349857Z,Paris,75015,FR,Point,"[2.306045999999999, 48.83701199998628]",Découvrez cet appartement charmant situé dans ...,Appartement lumineux - Quartier Alleray,Appartement à louer,"['3 pièces', '2 chambres', '64 m²', 'Étage 5/7']",2 650 €,3 pièces,64 m²,Étage 5/7,2 chambres
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2932,seloger,25UT5P77E2PI,2025-11-21T06:48:00Z,2025-11-22T07:16:17.023Z,Lyon 2ème,69002,FRA,Point,"[4.8261913, 45.7457853]",4 chambre(s) libre(s) dans une colocation de 4...,Chambre dans une colocation de 10m2,Studio à louer - logement étudiant,"['1 pièce', '4 chambres', '10 m²', '7ème étage']",510 €,1 pièce,10 m²,7ème étage,4 chambres
2933,seloger,259ARDJEYSUY,2025-11-20T09:12:00Z,2025-11-22T09:00:06.507Z,Paris 6ème,75006,FRA,Point,"[2.3206163, 48.8462324]",## Space\r\n\r\nNiché au 7 € étage avec ascens...,Appartement de 45m2,Appartement à louer,"['1 pièce', '45 m²', '7ème étage', 'dès le 13/...",3 000 €,1 pièce,45 m²,7ème étage,NaN
2934,seloger,25MTPA1TPQAW,2025-11-14T14:47:00Z,2025-11-14T14:51:05.416Z,Paris 18ème,75018,FRA,Point,"[2.3358418, 48.8904358]",Oiko Gestion vous propose un superbe studio de...,Superbe studio de 31m²,Appartement à louer,"['1 pièce', '31 m²', '2ème étage']",1 128 €,1 pièce,31 m²,2ème étage,NaN
2935,seloger,25BTJAKTZB2R,2025-11-20T07:41:00Z,2025-11-20T07:46:12.656Z,Paris 16ème,75016,FRA,Point,"[2.28324, 48.856]",L'Immobilière de Beauséjour vous propose en ex...,2 pièces • 55 m² • Paris 16ème • Jean Bologne,Appartement à louer,"['2 pièces', '1 chambre', '55 m²', '3ème étage']",2 295 €,2 pièces,55 m²,3ème étage,1 chambre
2936,seloger,256JGJP5HC47,2025-11-14T12:47:00Z,2025-11-14T12:51:05.087Z,Lyon 3ème,69003,FRA,MultiPolygon,"[[[[4.89486, 45.74378], [4.89188, 45.7391], [4...",Réf 414.10 - F2 - 9 Cours Richard Vitton 69003...,VITTON 9,Appartement à louer,"['2 pièces', '1 chambre', '57,4 m²', '2ème éta...",775 €,2 pièces,"57,4 m²",2ème étage,1 chambre

In [22]:
df = df.rename(columns={"metadata.creationDate": "creation_date",
    "metadata.updateDate": "update_date",
    "sections.location.address.city": "city",
    "sections.location.address.zipCode": "zip_code",
    "sections.location.address.country": "country",
    "sections.location.geometry.type": "geometry_type",
    "sections.location.geometry.coordinates": "geometry_coords",
    "sections.description.description": "description",
    "sections.description.headline": "headline",
    "sections.hardFacts.title": "title",
    "sections.hardFacts.keyfacts": "keyfacts",
    "sections.hardFacts.facts": "facts",
    "sections.hardFacts.price.value": "price_value"})

In [23]:
df.head()

,brand,id,creation_date,update_date,city,zip_code,country,geometry_type,geometry_coords,description,headline,title,keyfacts,price_value,numberOfRooms,livingSpace,numberOfFloors,numberOfBedrooms
0,seloger,25EC9GDFBT55,2025-11-20T08:56:00Z,2025-11-23T01:16:54.498Z,Paris 6ème,75006,FRA,Point,"[2.3387919, 48.8536809]",## Space\r\n\r\nThis accommodation is availabl...,Appartement de 34m2,Appartement à louer,"['1 pièce', '34 m²', '1er étage']",2 800 €,1 pièce,34 m²,1er étage,NaN
1,seloger,2524YZ9M2KYE,2025-11-06T14:14:00Z,2025-11-19T17:36:08.608Z,Lyon 5ème,69005,FRA,Point,"[4.794783, 45.758385]","26 B, rue des Aqueducs 69005 Lyon, au cœur du ...","Location F4 - 26 B, rue des Aqueducs 69005 Lyon",Appartement à louer,"['4 pièces', '3 chambres', '91,7 m²', 'Étage 7...",1 666 €,4 pièces,"91,7 m²",Étage 7/7,3 chambres
2,seloger,24KPL52W4HXP,2024-03-05T14:14:00Z,2025-10-30T01:20:07.218Z,Lyon 6ème,69006,FRA,Point,"[4.844802, 45.768051]",Au coeur du quartier FOCH - au 17 rue de Sèze ...,Appartement 3 pièces,Appartement à louer,"['3 pièces', '2 chambres', '63,5 m²', '4ème ét...",1 440 €,3 pièces,"63,5 m²",4ème étage,2 chambres
3,seloger,25IIW65P1F9X,2025-10-29T16:55:44.0438727Z,2025-10-29T16:55:44.0438708Z,Lyon,69005,FR,Point,"[4.827683999999999, 45.76254799999993]",Particulier loue F3 bis de 85 m² rue St Jean d...,ST JEAN 85m² grand T3 bis bcp cachet sans vis ...,Appartement à louer,"['3 pièces', '2 chambres', '85 m²', 'Étage 1/4']",1 280 €,3 pièces,85 m²,Étage 1/4,2 chambres
4,seloger,255ZQMFK4DAT,2025-11-03T10:08:08.2828323Z,2025-11-03T10:39:14.8349857Z,Paris,75015,FR,Point,"[2.306045999999999, 48.83701199998628]",Découvrez cet appartement charmant situé dans ...,Appartement lumineux - Quartier Alleray,Appartement à louer,"['3 pièces', '2 chambres', '64 m²', 'Étage 5/7']",2 650 €,3 pièces,64 m²,Étage 5/7,2 chambres

In [24]:
df.isna().sum()

brand                 0
id                    0
creation_date         0
update_date           0
city                  2
zip_code              0
country               0
geometry_type         0
geometry_coords       0
description           0
headline              0
title                 0
keyfacts              0
price_value           0
numberOfRooms         4
livingSpace           9
numberOfFloors      246
numberOfBedrooms    703
dtype: int64

In [6]:
df[df["livingSpace"].isnull()]

,brand,id,metadata.creationDate,metadata.updateDate,sections.location.address.city,sections.location.address.zipCode,sections.location.address.country,sections.location.geometry.type,sections.location.geometry.coordinates,sections.description.description,sections.description.headline,sections.hardFacts.title,sections.hardFacts.keyfacts,sections.hardFacts.price.value,numberOfRooms,livingSpace,numberOfFloors,numberOfBedrooms,availability,plotSpace
181,seloger,25NS1GNE8X2E,2025-07-04T17:04:00Z,2025-09-09T17:05:09.531Z,Paris 8ème,75008,FRA,MultiPolygon,"[[[[2.32093, 48.86302], [2.30174, 48.8635], [2...",LOCATION APPARTEMENT MEUBLE - 2 PIÈCES - PARIS...,Location Maison Meublée PARIS 75008,Maison à louer,"['2 pièces', '1 chambre']",2 300 €,2 pièces,NaN,NaN,1 chambre,NaN,NaN
606,seloger,25238VASYXP4,2025-11-20T20:12:00Z,2025-11-21T05:46:06.276Z,Lyon 3ème,69003,FRA,Point,"[4.8729941, 45.7571181]",Logement Manda ! Visitez et déposez votre doss...,Lyon,Studio à louer,"['4 pièces', '3 chambres', 'RDC']",550 €,4 pièces,NaN,RDC,3 chambres,NaN,NaN
1000,seloger,25HZ4K3CVWFW,2025-09-25T19:31:00Z,2025-11-06T21:36:14.716Z,Lyon 8ème,69008,FRA,Point,"[4.8838482, 45.7223654]",Logement Manda ! Visitez et déposez votre doss...,?? Chambre meublée en colocation moderne – Lyo...,Studio à louer,"['6 pièces', '5 chambres', '7ème étage']",466 €,6 pièces,NaN,7ème étage,5 chambres,NaN,NaN
1167,seloger,23GGAYAQZRIY,2023-08-21T09:01:00Z,2025-07-16T08:35:12.009Z,Lyon 5ème,69005,FRA,Point,"[4.786041, 45.756849]","Dans une résidence familiale, appartement réno...",À propos de ce bien,Appartement à louer,"['4 pièces', '3 chambres']",525 €,4 pièces,NaN,NaN,3 chambres,NaN,NaN
1311,seloger,25R5TNUZTLJ7,2025-11-20T09:36:00Z,2025-11-22T08:40:07.677Z,Paris 8ème,75008,FRA,Point,"[2.299989, 48.876917]",## Space\r\nCe logement est disponible pour un...,Appartement de 11m2,Appartement à louer,"['2 pièces', '6ème étage', 'dès le 23/12/2025']",1 350 €,2 pièces,NaN,6ème étage,NaN,dès le 23/12/2025,NaN
1535,seloger,25D7SZ439356,2025-11-13T15:18:00Z,2025-11-18T09:06:14.31Z,Lyon 4ème,69004,FRA,MultiPolygon,"[[[[4.84132, 45.77947], [4.84306, 45.77878], [...",Votre agence LES CLÉS D'ALEXIA vous propose u...,Colocation meublée pour 3 personnes – Caluire ...,Appartement à louer,"['4 pièces', '3 chambres', 'Étage 4/4']",500 €,4 pièces,NaN,Étage 4/4,3 chambres,NaN,NaN
1543,seloger,25CI3KMDDFTC,2025-11-17T22:02:00Z,2025-11-22T22:01:19.333Z,Lyon 5ème,69005,FRA,MultiPolygon,"[[[[4.81266, 45.74837], [4.81111, 45.7476], [4...",A louer appartement de type T3 avec balcon de ...,RUE DES CHEVAUCHEURS funiculaire ST JUST - T...,Appartement à louer,"['3 pièces', '2 chambres', 'Étage 1/2']",1 100 €,3 pièces,NaN,Étage 1/2,2 chambres,NaN,NaN
1708,seloger,25RYJZDDF6F1,2025-11-12T17:44:00Z,2025-11-12T17:46:14.27Z,Lyon 4ème,69004,FRA,MultiPolygon,"[[[[4.82928, 45.78293], [4.82929, 45.78293], [...",Particulier loue duplex meublé Croix Rousse.\r...,T2 Meuble Croix Rousse,Appartement à louer,"['2 pièces', '1 chambre', 'RDC']",885 €,2 pièces,NaN,RDC,1 chambre,NaN,NaN
1813,seloger,25UY424KVTZ9,2025-11-18T15:44:00Z,2025-11-22T21:05:06.045Z,Lyon 8ème,69008,FRA,Point,"[4.852754116, 45.729816437]","Au sein d'une copropriété, découvrez ce bel ap...",CHAMBRE COLOCATION - 69008 - 11m²,Appartement à louer,"['5 pièces', '1 chambre', '2ème étage', 'dès l...",600 €,5 pièces,NaN,2ème étage,1 chambre,dès le 17/12/2025,NaN
2575,seloger,251MGVC92B1D,2025-07-09T12:04:00Z,2025-08-09T16:36:10.843Z,Lyon 1er,69001,FRA,MultiPolygon,"[[[[4.83963, 45.76861], [4.83976, 45.76627], [...",LYON 2E ARRONDISSEMENT - A LOUER Chambre Loyer...,LYON 2EME CHAMBRE 800€ CC,Appartement à louer,"['1 chambre', 'Étage 4/5']",800 €,NaN,NaN,Étage 4/5,1 chambre,NaN,NaN
2658,seloger,252DLLWHZX2L,2025-10-06T16:34:00Z,2025-10-28T17:50:10.278Z,Lyon 8ème,69008,FRA,MultiPolygon,"[[[[4.85371, 45.72977], [4.85448, 45.71899], [...",Dans une maison indépendante avec jardin de 1...,Chambre de 15m2 Lyon 69008,Appartement à louer,['1 chambre'],450 €,NaN,NaN,NaN,1 chambre,NaN,NaN
2739,seloger,257YQELM2V69,2025-09-29T19:49:00Z,2025-11-06T21:36:20.804Z,Lyon 8ème,69008,FRA,Point,"[4.8838482, 45.7223654]",Logement Manda ! Visitez et déposez votre doss...,?? Chambre meublée en colocation moderne – Lyo...,Studio à louer,"['6 pièces', '5 chambres', '7ème étage']",460 €,6 pièces,NaN,7ème étage,5 chambres,NaN,NaN
2769,seloger,25A6B9TC8AKW,2025-11-20T08:54:00Z,2025-11-22T08:25:09.297Z,Paris 18ème,75018,FRA,Point,"[2.3525534, 48.8905111]",Découvrez ce magnifique studio entièrement meu...,Maison de 12m2,Maison à louer,"['1 pièce', 'dès le 01/01/2026']",1 195 €,1 pièce,NaN,NaN,NaN,dès le 01/01/2026,NaN
3123,seloger,25VNI2JNRVGU,2025-11-12T17:44:00Z,2025-11-12T17:46:14.036Z,Lyon 9ème,69009,FRA,MultiPolygon,"[[[[4.81036, 45.76018], [4.81238, 45.75868], [...",Appartement à louer - Lyon 9ème\r\nAppartement...,Appartement à louer Lyon 9,Appartement à louer,NaN,850 €,NaN,NaN,NaN,NaN,NaN,NaN
3174,seloger,256PBKPWDLZB,2025-10-06T16:30:00Z,2025-10-28T17:46:10.997Z,Lyon 1er,69001,FRA,MultiPolygon,"[[[[4.8269, 45.77195], [4.828, 45.77154], [4.8...",je propose a partir de maintenant une colocati...,recherche colocataire h pour colocation centre...,Appartement à louer,['2 pièces'],500 €,2 pièces,NaN,NaN,NaN,NaN,NaN

In [25]:
df.shape[0]

2937

In [26]:
df = df.dropna(subset=['livingSpace'])

In [27]:
df.isna().sum()

brand                 0
id                    0
creation_date         0
update_date           0
city                  2
zip_code              0
country               0
geometry_type         0
geometry_coords       0
description           0
headline              0
title                 0
keyfacts              0
price_value           0
numberOfRooms         4
livingSpace           0
numberOfFloors      244
numberOfBedrooms    701
dtype: int64

In [28]:
df.shape[0]

2928

In [ ]:
# TODO: mettre sur github
# TODO: mettre les bons types sur les colonnes
# TODO: finir de cleaner -> supprimer les doublons , checker les unités , écrire les nombres avec des regex
# TODO: structurer le projet 
# TODO: faire des graphs -> histogramme avec tous les points des différents m2 et une droite moyenne + une droite médiane
# TODO: app streamlit